- name: Install Docker
  hosts: all

  tasks:
    - name: Install Dependencies
      package:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - ca-certificates
        - curl
        - gnupg
        - python3-pip

    - name: Install PIP modules for docker
      pip:
        name: docker
        state: present
     
    - name: Add GPG Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        keyring: /etc/apt/keyrings/docker.gpg

    - name: Add Docker Repository
      apt_repository:
        repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable

    - name: Install Docker Packages
      package:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin

    - name: Running First Container
      docker_container:
        name: myFirstContainer
        image: hello-world
